#!/usr/bin/env bash
cd /home/sherlock/Programs/CloudFail
source /home/sherlock/Programs/CloudFail/CloudFail-venv/bin/activate
/home/sherlock/Programs/CloudFail/CloudFail-venv/bin/python3 /home/sherlock/Programs/CloudFail/cloudfail.py "$@"
