#!/usr/bin/env bash
cd /home/sherlock/Programs/infoga
source /home/sherlock/Programs/infoga/infoga-venv/bin/activate
/home/sherlock/Programs/infoga/infoga-venv/bin/python2.7 /home/sherlock/Programs/infoga/infoga.py "$@"
